root = "."
testdata_dir = "testdata"
tmp_dir = "bin"

[build]
  args_bin = []
  bin = "./bin/despensa"
  cmd = "make dev/build"
  delay = 1000
  exclude_dir = [
    "bin", 
    "database",
    "node_modules", 
  ]
  exclude_file = ["Makefile", ".gitignore", "README.md"]
  exclude_regex = ["_test.go" ]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "css", "js", "jpeg", "jpg", "gif", "png", "svg", "webp", "ico", "txt"]
  include_file = []
  kill_delay = "5s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = true
  stop_on_error = true

[color]
  app = "red"
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = true

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = false
  keep_scroll = true
