# fly.toml app configuration file generated for despensa on 2024-03-05T12:44:35Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'despensa'
primary_region = 'mad'

[build]

[[mounts]]
  source = 'despensa_data'
  destination = '/home/nonroot/data'
  initial_size = '1gb'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
